### ISSUE TITLE
Falta validação para valores negativos.

### ISSUE THREAD

**Issue by gbschanz** [gbschanz/ticket-machine-ajustado#4]
https://github.com/gbschanz/ticket-machine-ajustado/blob/2dc2ea8171b38c69abd68ccdabf2d5c0159a2083/Source%20Code%20Inspection/src/br/calebe/ticketmachine/core/PapelMoeda.java#L12-L15

**Comment by barbieriraketti** [comment]
public PapelMoeda(int valor, int quantidade) {
        if (valor <= 0) {
            throw new IllegalArgumentException("O valor da nota deve ser positivo.");
        }
        if (quantidade <= 0) {
            throw new IllegalArgumentException("A quantidade de notas deve ser positiva.");
        }
        this.valor = valor;
        this.quantidade = quantidade;
    }

ARRUMADO
